name: myworkflow
on: 
  # push:
  #   branches: 
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    # inputs:
    #   name:
    #     description: 'Name of the person'
    #     required: true
    #     type: string
    #     default: 'John Doe'

env:
  MY_ENV_VAR: "This is an global environment variable by"


jobs:

  # myjob:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: run checkout
  #       uses: actions/checkout@v7
  #     - name: run commands
  #       run: ls -lrt
  #     - name: run echo
  #       run: echo "actions created by ${{inputs.name}}"
  # job1:
  #   runs-on: ubuntu-latest
  #   env:
  #     job_env_var: "job1 env var by ${{inputs.name}}"
  #   steps:
  #     - name: step 1
  #       run: echo "This is step 1"
  #     - name: step 2
  #       if: ${{ inputs.name != 'John Doe' }}
  #       run: echo ${{env.MY_ENV_VAR}}
  #     - name: step 3
  #       if: ${{ inputs.name == 'John Doe' }}
  #       run: echo ${{env.job_env_var}}
  # job2:
  #   runs-on: ubuntu-latest
  #   env:
  #     job_env_var: "job2 by ${{inputs.name}}"
  #   needs: job1
  #   steps:
  #     - name: step 1
  #       run: echo ${{env.job_env_var}}
  #     - name: step 2
  #       run: echo ${{env.MY_ENV_VAR}}

    # job-matrix:
    #   runs-on: ${{ matrix.os }}
    #   strategy:
    #     matrix:
    #       name: 
    #         - John Doe
    #         - Jane Smith
    #         - Alice Johnson
    #       version: 
    #         - 1.0
    #         - 2.0
    #       os: 
    #         - ubuntu-latest
    #         - windows-latest
    #   steps:
    #     - name: run echo
    #       run: echo "Hello, ${{ matrix.name }}!"
    #     - name: run echo version
    #       run: echo "Version ${{ matrix.version }}"
    #     - name: run echo os
    #       run: echo "OS  ${{ matrix.os }}"
