name: myworkflow
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  running_commands:
    runs-on: ubuntu-latest
    steps:
      - name: run checkout
        uses: actions/checkout@v7
      - name: run commands
        run: ls -lrt
      - name: run echo
        run: echo "finished workflow job"
